apiVersion: v2
name: model-serving-onnx-rust
description: Helm chart for serving ONNX models with ONNX Runtime GenAI (Rust server)
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: bjw-template
    version: "0.1.0"
    repository: "file://../bjw-template"
maintainers:
  - name: onnx-ai-helm