apiVersion: v2
name: model-serving-llamacpp
description: Helm chart for serving GGUF models with llama.cpp
type: application
version: 0.1.0
appVersion: "b4093"
dependencies:
  - name: bjw-template
    version: "0.1.0"
    repository: "file://../bjw-template"
maintainers:
  - name: onnx-ai-helm