apiVersion: v2
name: model-serving-vllm
description: Helm chart for serving Safetensors/AWQ/GPTQ models with vLLM
type: application
version: 0.1.0
appVersion: "0.6.3"
dependencies:
  - name: bjw-template
    version: "0.1.0"
    repository: "file://../bjw-template"
maintainers:
  - name: onnx-ai-helm