name: Security Audit
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    uses: ADORSYS-GIS/ai-governance/.github/workflows/security-gates.yml@main
    secrets: inherit
    with:
      trivy-scan-type: 'config'
      trivy-target: 'charts/'
